networks:
  smtp-net:
    driver: "bridge"

services:
  fake-smtp:
    build: .
    container_name: fake-smtp
    ports:
      - "2525:25"
    volumes:
      - ./output:/output
    networks:
      - smtp-net
